# Generated by Django 6.1 on 2026-08-20 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_photo_title_alter_photo_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='aperture',
            field=models.CharField(blank=True, help_text='e.g. f/2.8', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='camera_model',
            field=models.CharField(blank=True, help_text='e.g. Sony A7IV', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(blank=True, help_text='e.g. 50mm', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='iso',
            field=models.IntegerField(blank=True, help_text='e.g. 100', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Pokhara, Nepal', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='shutter_speed',
            field=models.CharField(blank=True, help_text='e.g. 1/1000s', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.category'),
        ),
    ]
