# Generated by Django 6.1 on 2026-09-03 12:40

from django.db import migrations, models


def clear_fake_avatars(apps, schema_editor):
    Profile = apps.get_model('App', 'Profile')
    Profile.objects.filter(avatar='avatars/default.png').update(avatar='')


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.RunPython(clear_fake_avatars, migrations.RunPython.noop),
    ]